server:
   port: 8888
spring:
   profiles:
      active: native #perfil por defecto de spirng cloud config
   application:
      name: config-server
   cloud:
      config:
         server:
            native:
               searchLocations: classpath:/configurations #nombre de rutas donde se encuentran los archivos de configuracion