server:
   port: 8090
   #por defecto spring funciona en el 8080
   #en este caso lo cambiamos para que no trabajen todos desde el mismo puerto

spring:
   application:
      name: msvc-student
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver #config database mysql
      url: jdbc:mysql://localhost:3306/studentsdb
      username: root
      password: Bleachh2233+
   jpa:
      hibernate:
         ddl-auto: create #cada que se levante la app genere automaticamente las tablas
         database: mysql
         database-platform: org.hibernate.dialect.MySQL8Dialect

#config msvc para que se registre en Eureka
eureka:
   instance:
      hostname: localhost
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka